name: Generate GitHub Metrics

on:
  schedule: # Runs once a day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKENNN }} # Your GitHub token secret here
          user: drapraks # Replace with your GitHub username
          template: classic
          config_timezone: Asia/Jakarta # Optional: set to your timezone
          plugin_isocalendar: yes
          plugin_contributors: yes
          plugin_languages: yes
          plugin_activity: yes
          plugin_activity_load: 300 # Number of recent activities to fetch
          plugin_languages_sections: recent, commits, repositories
          plugin_languages_analysis_timeout: 10 # Optional: increase timeout if needed
          plugin_achievements: yes
          plugin_traffic: yes
